.\" Manpage for imshare.
.\" Contact job@x25 to correct errors or typos.
.TH man 8 "01 Mar 2015" "1.0" "imshare man page"
.SH NAME
imshare \- Screen capture tool
.SH SYNOPSIS
imshare [<filename> [...]]
.SH DESCRIPTION
Captures screen selection and upload images to imgur.com.
.SH OPTIONS
The imshare does not take any options for screen capture. However, you can supply the image file names.
.SH SEE ALSO
scrot(1), import(1)
.SH BUGS
No known bugs.
.SH AUTHOR
x25 (https://github.com/x25/imshare)
